/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author tate
 */
public class JDlgProdutosNovoIA extends javax.swing.JDialog {

    /**
     * Creates new form JDlgProdutosNovoIA
     */
    public JDlgProdutosNovoIA(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Inclusão de Produtos");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBtnOk = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        nome_tto = new javax.swing.JTextField();
        categoria_tto = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        valorCompra_tto = new javax.swing.JTextField();
        descricao_tto = new javax.swing.JPasswordField();
        valorVenda_tto = new javax.swing.JFormattedTextField();
        idprodutos_tto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jBtnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok.png"))); // NOI18N
        jBtnOk.setText("OK");
        jBtnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOkActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnOk);

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnCancelar.setText("CANCELAR");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnCancelar);

        jLabel3.setText("Nome");

        nome_tto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nome_ttoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nome_ttoFocusLost(evt);
            }
        });

        categoria_tto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Xbox", "PlayStation 4", "Wii U" }));
        categoria_tto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                categoria_ttoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                categoria_ttoFocusLost(evt);
            }
        });

        jLabel7.setText("Descrição");

        jLabel5.setText("Valor da Compra");

        jLabel1.setText("Código");

        valorCompra_tto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                valorCompra_ttoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                valorCompra_ttoFocusLost(evt);
            }
        });

        descricao_tto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                descricao_ttoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                descricao_ttoFocusLost(evt);
            }
        });
        descricao_tto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descricao_ttoActionPerformed(evt);
            }
        });

        valorVenda_tto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                valorVenda_ttoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                valorVenda_ttoFocusLost(evt);
            }
        });

        idprodutos_tto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                idprodutos_ttoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                idprodutos_ttoFocusLost(evt);
            }
        });

        jLabel6.setText("Valor da Venda");

        jLabel8.setText("Categoria");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(idprodutos_tto, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nome_tto, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(valorCompra_tto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(valorVenda_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(categoria_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(descricao_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idprodutos_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valorVenda_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nome_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descricao_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(valorCompra_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(categoria_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOkActionPerformed
        setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnOkActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void nome_ttoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nome_ttoFocusGained

    }//GEN-LAST:event_nome_ttoFocusGained

    private void nome_ttoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nome_ttoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_ttoFocusLost

    private void categoria_ttoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_categoria_ttoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_categoria_ttoFocusGained

    private void categoria_ttoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_categoria_ttoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_categoria_ttoFocusLost

    private void valorCompra_ttoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valorCompra_ttoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_valorCompra_ttoFocusGained

    private void valorCompra_ttoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valorCompra_ttoFocusLost

    }//GEN-LAST:event_valorCompra_ttoFocusLost

    private void descricao_ttoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_descricao_ttoFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_descricao_ttoFocusGained

    private void descricao_ttoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_descricao_ttoFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_descricao_ttoFocusLost

    private void descricao_ttoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descricao_ttoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descricao_ttoActionPerformed

    private void valorVenda_ttoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valorVenda_ttoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_valorVenda_ttoFocusGained

    private void valorVenda_ttoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valorVenda_ttoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_valorVenda_ttoFocusLost

    private void idprodutos_ttoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idprodutos_ttoFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_idprodutos_ttoFocusGained

    private void idprodutos_ttoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idprodutos_ttoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_idprodutos_ttoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgProdutosNovoIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgProdutosNovoIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgProdutosNovoIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgProdutosNovoIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgProdutosNovoIA dialog = new JDlgProdutosNovoIA(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> categoria_tto;
    private javax.swing.JPasswordField descricao_tto;
    private javax.swing.JTextField idprodutos_tto;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nome_tto;
    private javax.swing.JTextField valorCompra_tto;
    private javax.swing.JFormattedTextField valorVenda_tto;
    // End of variables declaration//GEN-END:variables
}
