/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.ComprasProdutosTto;
import bean.ComprasTto;
import bean.FornecedoresTto;
import bean.FuncionariosTto;
import dao.ComprasProdutos_DAO;
import dao.Compras_DAO;
import dao.Fornecedores_DAO;
import dao.Funcionarios_DAO;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import tools.Util;

/**
 *
 * @author tate
 */
public class JDlgCompras extends javax.swing.JDialog {

    MaskFormatter mascaraData;

    private boolean incluindo;
    Compras_DAO compras_DAO;
    ComprasTto compras;
    ComprasProdutosControle comprasProdutosControle;
    ComprasControle comprasControle;
    JDlgComprasProdutos jDlgComprasProdutos;

    /**
     * Creates new form JDlgPedidos
     */
    public JDlgCompras(java.awt.Frame parent, boolean modal) {

        super(parent, modal);
        initComponents();
        jDlgComprasProdutos = new JDlgComprasProdutos(null, true);
        setTitle("Tela de Compras");
        setLocationRelativeTo(null);
        compras_DAO = new Compras_DAO();
        compras = new ComprasTto();
        ComprasProdutos_DAO comprasProdutos_DAO = new ComprasProdutos_DAO();
        List lista = new ArrayList();
        comprasProdutosControle = new ComprasProdutosControle();
        comprasProdutosControle.setList(lista);
        jTable1.setModel(comprasProdutosControle);

        Util.habilitar(true, jBtnIncluir, jBtnPesquisar);
        Util.habilitar(false, jBtnIncluirLateral, jBtnAlterarLateral, jBtnExcluirLateral,
                jBtnConfirmar, jBtnCancelar, jBtnAlterar, jBtnExcluir,
                jTxtNumPedido_tto, jFmtData_tto, jCboFornecedor_tto, jCboFuncionario_tto,
                jTxtTotal_tto);

        //AAAAAAAAA
        Fornecedores_DAO fornecedores_DAO = new Fornecedores_DAO();
        List listaFornecedores = fornecedores_DAO.listAll();

        for (int i = 0; i < listaFornecedores.size(); i++) {
            FornecedoresTto fornecedores = (FornecedoresTto) listaFornecedores.get(i);
            jCboFornecedor_tto.addItem(fornecedores);
        }

        //BBBBBBBBBB
        Funcionarios_DAO funcionarios_DAO = new Funcionarios_DAO();
        List listaFuncionarios = funcionarios_DAO.listAll();

        for (int i = 0; i < listaFuncionarios.size(); i++) {
            FuncionariosTto funcionarios = (FuncionariosTto) listaFuncionarios.get(i);
            jCboFuncionario_tto.addItem(funcionarios);
        }

        try {
            mascaraData = new MaskFormatter("##/##/####");
        } catch (ParseException ex) {
            Logger.getLogger(JDlgUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        jFmtData_tto.setFormatterFactory(new DefaultFormatterFactory(mascaraData));

    }

    public ComprasTto viewBean() {
        ComprasTto compras = new ComprasTto();

        compras.setIdcomprasTto(Util.strInt(jTxtNumPedido_tto.getText()));
        compras.setFornecedoresTto((FornecedoresTto) jCboFornecedor_tto.getSelectedItem());
        compras.setFuncionariosTto((FuncionariosTto) jCboFuncionario_tto.getSelectedItem());
        compras.setDataTto(Util.strDate(jFmtData_tto.getText()));
        compras.setTotalTto(Util.strDouble(jTxtTotal_tto.getText()));

        return compras;
    }

    public void beanView(ComprasTto compras) {

        jTxtNumPedido_tto.setText(Util.intStr(compras.getIdcomprasTto()));
        jCboFornecedor_tto.setSelectedItem(compras.getFornecedoresTto());
        jCboFuncionario_tto.setSelectedItem(compras.getFuncionariosTto());
        jFmtData_tto.setText(Util.dateStr(compras.getDataTto()));
        jTxtTotal_tto.setText(Util.doubleStr(compras.getTotalTto()));

        ComprasProdutos_DAO comprasProdutos_DAO = new ComprasProdutos_DAO();
        List listaProd = (List) comprasProdutos_DAO.listProdutos(compras);

        comprasProdutosControle.setList(listaProd);
    }

    public int getSelectedRowProd() {
        return jTable1.getSelectedRow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBtnIncluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jBtnPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBtnIncluirLateral = new javax.swing.JButton();
        jBtnAlterarLateral = new javax.swing.JButton();
        jBtnExcluirLateral = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTxtNumPedido_tto = new javax.swing.JTextField();
        jFmtData_tto = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtTotal_tto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCboFornecedor_tto = new javax.swing.JComboBox<FornecedoresTto>();
        jLabel6 = new javax.swing.JLabel();
        jCboFuncionario_tto = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar_1.png"))); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir_1.png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gravar.png"))); // NOI18N
        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnIncluir)
                .addGap(18, 18, 18)
                .addComponent(jBtnAlterar)
                .addGap(18, 18, 18)
                .addComponent(jBtnExcluir)
                .addGap(18, 18, 18)
                .addComponent(jBtnConfirmar)
                .addGap(18, 18, 18)
                .addComponent(jBtnCancelar)
                .addGap(18, 18, 18)
                .addComponent(jBtnPesquisar)
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnIncluir)
                    .addComponent(jBtnAlterar)
                    .addComponent(jBtnExcluir)
                    .addComponent(jBtnConfirmar)
                    .addComponent(jBtnCancelar)
                    .addComponent(jBtnPesquisar))
                .addGap(21, 21, 21))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Produto", "Quantidade", "Valor unitário", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jBtnIncluirLateral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnIncluirLateral.setText("Incluir");
        jBtnIncluirLateral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirLateralActionPerformed(evt);
            }
        });

        jBtnAlterarLateral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar_1.png"))); // NOI18N
        jBtnAlterarLateral.setText("Alterar");
        jBtnAlterarLateral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarLateralActionPerformed(evt);
            }
        });

        jBtnExcluirLateral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir_1.png"))); // NOI18N
        jBtnExcluirLateral.setText("Excluir");
        jBtnExcluirLateral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirLateralActionPerformed(evt);
            }
        });

        jLabel1.setText("NumPedido");

        jLabel2.setText("Total");

        jLabel3.setText("Data");

        jLabel5.setText("Fornecedor");

        jLabel6.setText("Funcionário");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jTxtNumPedido_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFmtData_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jCboFornecedor_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jCboFuncionario_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jTxtTotal_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnIncluirLateral)
                            .addComponent(jBtnAlterarLateral)
                            .addComponent(jBtnExcluirLateral, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTxtNumPedido_tto, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                                .addComponent(jFmtData_tto)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jCboFornecedor_tto)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jCboFuncionario_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtTotal_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBtnIncluirLateral)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnAlterarLateral)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnExcluirLateral)
                        .addGap(98, 98, 98)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
        // TODO add your handling code here:
        if (compras != null) {
            ComprasProdutos_DAO comprasProdutos_DAO = new ComprasProdutos_DAO();
            ComprasProdutosTto comprasProdutosTto;
            for (int linha = 0; linha < jTable1.getRowCount(); linha++) {
                comprasProdutosTto = comprasProdutosControle.getBean(linha);
                comprasProdutos_DAO.delete(comprasProdutosTto);

            }
        } else {
            Util.mensagem("Realize uma pesquisa antes");
        }
        incluindo = false;
        Util.habilitar(false, jBtnIncluir, jBtnAlterar, jBtnExcluir, jBtnPesquisar);
        Util.habilitar(true, jTxtNumPedido_tto, jFmtData_tto, jCboFornecedor_tto, jCboFuncionario_tto, jTxtTotal_tto,
                jBtnConfirmar, jBtnCancelar, jBtnIncluirLateral, jBtnAlterarLateral, jBtnExcluirLateral);

        // NAO ESTA COM LOGICA E NAO SEI O MOTIVO
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        comprasProdutosControle.setList(new ArrayList());
        Util.mensagem("Cancelamento concluído");
        Util.limparCampos(jTxtNumPedido_tto, jFmtData_tto, jCboFornecedor_tto, jCboFuncionario_tto, jTxtTotal_tto);
        Util.habilitar(true, jBtnIncluir, jBtnPesquisar);
        Util.habilitar(false, jBtnIncluirLateral, jBtnAlterarLateral, jBtnExcluirLateral,
                jBtnConfirmar, jBtnCancelar, jBtnAlterar, jBtnExcluir,
                jTxtNumPedido_tto, jFmtData_tto, jCboFornecedor_tto, jCboFuncionario_tto,
                jTxtTotal_tto);
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        // TODO add your handling code here:
        Util.limparCampos(jTxtNumPedido_tto, jFmtData_tto, jCboFornecedor_tto, jCboFuncionario_tto, jTxtTotal_tto);
        comprasProdutosControle.setList(new ArrayList());
        jTxtNumPedido_tto.grabFocus();
        incluindo = true;
        compras = new ComprasTto();

        Util.habilitar(true, jBtnIncluirLateral, jBtnAlterarLateral, jBtnExcluirLateral, jBtnConfirmar, jBtnCancelar,
                jTxtNumPedido_tto, jFmtData_tto, jCboFornecedor_tto, jCboFuncionario_tto, jTxtTotal_tto);
        Util.habilitar(false, jBtnIncluir, jBtnAlterar, jBtnExcluir, jBtnPesquisar);
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        // TODO add your handling code here:
        if (compras != null) {
            if (Util.perguntar("Deseja excluir o pedido?") == true) {
                ComprasProdutos_DAO comprasProdutos_DAO = new ComprasProdutos_DAO();
                ComprasProdutosTto comprasProdutosTto;
                for (int linha = 0; linha < jTable1.getRowCount(); linha++) {
                    comprasProdutosTto = comprasProdutosControle.getBean(linha);
                    comprasProdutos_DAO.delete(comprasProdutosTto);
                }
                compras_DAO.delete(compras);
            }
        } else {
            Util.mensagem("Deve ser realizada uma pesquisa antes");
        }
        comprasProdutosControle.setList(new ArrayList());

        Util.limparCampos(jTxtNumPedido_tto, jFmtData_tto, jCboFornecedor_tto, jCboFuncionario_tto, jTxtTotal_tto);

        Util.habilitar(false, jTxtNumPedido_tto, jFmtData_tto, jCboFornecedor_tto, jCboFuncionario_tto, jTxtTotal_tto,
                jBtnAlterar, jBtnExcluir,
                jBtnConfirmar, jBtnCancelar, jBtnIncluirLateral, jBtnAlterarLateral, jBtnExcluirLateral);
        Util.habilitar(true, jBtnIncluir, jBtnPesquisar);
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
        // TODO add your handling code here:
        JDlgComprasPesquisa jDlgComprasPesquisa = new JDlgComprasPesquisa(null, true);
        jDlgComprasPesquisa.setTelaAnterior(this);
        jDlgComprasPesquisa.setVisible(true);

        Util.habilitar(true, jBtnAlterar, jBtnExcluir);
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
        compras = viewBean();
        if (incluindo == true) {
            compras_DAO.insert(compras);
            ComprasProdutos_DAO comprasProdutos_DAO = new ComprasProdutos_DAO();
            ComprasProdutosTto comprasProdutosTto;
            for (int linha = 0; linha < jTable1.getRowCount(); linha++) {
                comprasProdutosTto = comprasProdutosControle.getBean(linha);
                comprasProdutosTto.setComprasTto(compras);
                comprasProdutos_DAO.insert(comprasProdutosTto);
            }
        } else {
            compras_DAO.update(compras);
            //remover todos os pedidos produtos deste pedido

            //incluir todos os pedidosProduto que estao no jtable
            ComprasProdutos_DAO comprasProdutos_DAO = new ComprasProdutos_DAO();
            ComprasProdutosTto comprasProdutosTto;
            for (int linha = 0; linha < jTable1.getRowCount(); linha++) {
                comprasProdutosTto = comprasProdutosControle.getBean(linha);
                comprasProdutosTto.setComprasTto(compras);
                comprasProdutos_DAO.insert(comprasProdutosTto);
            }
        }
        Util.habilitar(false, jTxtNumPedido_tto, jFmtData_tto, jCboFornecedor_tto, jCboFuncionario_tto, jTxtTotal_tto,
                jBtnAlterar, jBtnExcluir,
                jBtnConfirmar, jBtnCancelar, jBtnIncluirLateral, jBtnAlterarLateral, jBtnExcluirLateral);
        Util.habilitar(true, jBtnIncluir, jBtnPesquisar);
        comprasProdutosControle.setList(new ArrayList());
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnExcluirLateralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirLateralActionPerformed
        // TODO add your handling code here:
        if (getSelectedRowProd() == -1) {
            Util.mensagem("Nenhuma linha selecionada");
        } else {
            if (Util.perguntar("Deseja excluir o produto?") == true) {
                comprasProdutosControle.removeBean(getSelectedRowProd());
            }
        }
    }//GEN-LAST:event_jBtnExcluirLateralActionPerformed

    private void jBtnAlterarLateralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarLateralActionPerformed
        // TODO add your handling code here:
        jDlgComprasProdutos.setTitle("Alteração");
        jDlgComprasProdutos.setTelaAnterior(this);
        int linSel = jTable1.getSelectedRow();
        ComprasProdutosTto comprasProdutosTto = (ComprasProdutosTto) comprasProdutosControle.getBean(linSel);
        jDlgComprasProdutos.beanView(comprasProdutosTto);
        jDlgComprasProdutos.setVisible(true);
    }//GEN-LAST:event_jBtnAlterarLateralActionPerformed

    private void jBtnIncluirLateralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirLateralActionPerformed
        // TODO add your handling code here:
        jDlgComprasProdutos.setTitle("Inclusão de produtos");
        jDlgComprasProdutos.setTelaAnterior(this);
        jDlgComprasProdutos.setVisible(true);
    }//GEN-LAST:event_jBtnIncluirLateralActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgCompras dialog = new JDlgCompras(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnAlterarLateral;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnExcluirLateral;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnIncluirLateral;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JComboBox<FornecedoresTto> jCboFornecedor_tto;
    private javax.swing.JComboBox<FuncionariosTto> jCboFuncionario_tto;
    private javax.swing.JFormattedTextField jFmtData_tto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTxtNumPedido_tto;
    private javax.swing.JTextField jTxtTotal_tto;
    // End of variables declaration//GEN-END:variables
}
