/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.ComprasProdutosTto;
import bean.ProdutosTto;
import dao.ComprasProdutos_DAO;
import dao.Produtos_DAO;
import java.util.List;
import tools.Util;

/**
 *
 * @author tate
 */
public class JDlgComprasProdutos extends javax.swing.JDialog {

    JDlgCompras jDlgCompras;
    Produtos_DAO produtos_DAO;
    ComprasProdutos_DAO comprasProdutos_DAO;

    /**
     * Creates new form JDlgComprasProdutos
     */
    public JDlgComprasProdutos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Inclusão de produtos");
        setLocationRelativeTo(null);
        produtos_DAO = new Produtos_DAO();
        List lista = (List) produtos_DAO.listAll();

        Util.habilitar(false, jTxtTotal_tto);

        for (int i = 0; i < lista.size(); i++) {
            jCboProdutos.addItem((ProdutosTto) lista.get(i));
        }

    }

    public void setTelaAnterior(JDlgCompras jDlgCompras) {
        this.jDlgCompras = jDlgCompras;
    }

    public void beanView(ComprasProdutosTto comprasProdutosTto) {
        jCboProdutos.setSelectedItem(comprasProdutosTto.getComprasTto());
        jTxtQuantidade_tto.setText(Integer.toString(comprasProdutosTto.getQuantidadeTto()));
        jTxtValorUnitario_tto.setText(Double.toString(comprasProdutosTto.getValorUnitarioTto()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBtnOk = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jTxtTotal_tto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTxtValorUnitario_tto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtQuantidade_tto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jCboProdutos = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBtnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok.png"))); // NOI18N
        jBtnOk.setText("OK");
        jBtnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOkActionPerformed(evt);
            }
        });

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar_1.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnOk)
                .addGap(18, 18, 18)
                .addComponent(jBtnCancelar)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnOk))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel1.setText("Total");

        jTxtValorUnitario_tto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtValorUnitario_ttoKeyReleased(evt);
            }
        });

        jLabel2.setText("Valor unitário");

        jTxtQuantidade_tto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtQuantidade_ttoActionPerformed(evt);
            }
        });
        jTxtQuantidade_tto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtQuantidade_ttoKeyReleased(evt);
            }
        });

        jLabel3.setText("Quantidade");

        jCboProdutos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCboProdutosItemStateChanged(evt);
            }
        });

        jLabel4.setText("Produtos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jCboProdutos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jTxtQuantidade_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTxtValorUnitario_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jTxtTotal_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jCboProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtTotal_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtQuantidade_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtValorUnitario_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        Util.limparCampos();
        setVisible(false);
        Util.mensagem("Cancelamento concluído");
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOkActionPerformed
        // TODO add your handling code here:
        ComprasProdutosTto comprasProdutosTto = new ComprasProdutosTto();
        comprasProdutosTto.setProdutosTto((ProdutosTto) jCboProdutos.getSelectedItem());
        comprasProdutosTto.setValorUnitarioTto(Util.strInt(jTxtQuantidade_tto.getText()));;
        comprasProdutosTto.setValorUnitarioTto(Util.strDouble(jTxtValorUnitario_tto.getText()));

        if (getTitle().toUpperCase().substring(0, 1).equals("I")) {
            jDlgCompras.comprasProdutosControle.addBean(comprasProdutosTto);
        } else {
            jDlgCompras.comprasProdutosControle.updateBean(jDlgCompras.getSelectedRowProd(), comprasProdutosTto);
        }

        setVisible(false);
    }//GEN-LAST:event_jBtnOkActionPerformed

    private void jTxtQuantidade_ttoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtQuantidade_ttoActionPerformed
        // TODO add your handling code here:
        if (jTxtQuantidade_tto.getText().isEmpty() == false) {
            double unitario = Util.strDouble(jTxtValorUnitario_tto.getText());
            double quantidade = Util.strDouble(jTxtQuantidade_tto.getText());
            jTxtTotal_tto.setText(String.valueOf(quantidade * unitario));
        } else {
            jTxtTotal_tto.setText("0");
        }
    }//GEN-LAST:event_jTxtQuantidade_ttoActionPerformed

    private void jCboProdutosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCboProdutosItemStateChanged
        // TODO add your handling code here:
        jTxtQuantidade_tto.setText("1");
        ProdutosTto produtosTto = (ProdutosTto) jCboProdutos.getSelectedItem();
        jTxtValorUnitario_tto.setText(Util.doubleStr(produtosTto.getValorUnitarioTto()));
        jTxtTotal_tto.setText(jTxtValorUnitario_tto.getText());
    }//GEN-LAST:event_jCboProdutosItemStateChanged

    private void jTxtQuantidade_ttoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtQuantidade_ttoKeyReleased
        // TODO add your handling code here:
        if (jTxtQuantidade_tto.getText().isEmpty() == false) {
            double unitario = Util.strDouble(jTxtValorUnitario_tto.getText());
            double quantidade = Util.strDouble(jTxtQuantidade_tto.getText());
            jTxtTotal_tto.setText(Util.doubleStr(quantidade * unitario));
        } else {
            jTxtTotal_tto.setText("0");
        }
    }//GEN-LAST:event_jTxtQuantidade_ttoKeyReleased

    private void jTxtValorUnitario_ttoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtValorUnitario_ttoKeyReleased
        // TODO add your handling code here:
        if (jTxtValorUnitario_tto.getText().isEmpty() == false) {
            double quantidade = Util.strDouble(jTxtQuantidade_tto.getText());
            double unitario = Util.strDouble(jTxtValorUnitario_tto.getText());
            jTxtTotal_tto.setText(Util.doubleStr(unitario * quantidade));
        } else {
            jTxtTotal_tto.setText("0");
        }
    }//GEN-LAST:event_jTxtValorUnitario_ttoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgComprasProdutos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgComprasProdutos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgComprasProdutos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgComprasProdutos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgComprasProdutos dialog = new JDlgComprasProdutos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnOk;
    private javax.swing.JComboBox<ProdutosTto> jCboProdutos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxtQuantidade_tto;
    private javax.swing.JTextField jTxtTotal_tto;
    private javax.swing.JTextField jTxtValorUnitario_tto;
    // End of variables declaration//GEN-END:variables
}
