/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.UsuariosTto;
import dao.Usuarios_DAO;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import tools.Util;

/**
 *
 * @author u10475493109
 */
public class JDlgUsuarios extends javax.swing.JDialog {

    /**
     * Creates new form GDlgUsuarios
     */
    private boolean incluindo;
    MaskFormatter mascaraCPF, mascaraDataNascimento;

    //variavel global declarada entre o construtor e a classe private boolean incluindo;
    //pode colocar em qualquer local menos no metodo
    //variável global é definida quando declaramos uma variável fora de qualquer função
    /**
     * Creates new form JDlgUsuarios
     */
    public JDlgUsuarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de usuários");
        setLocationRelativeTo(null);
        try {
            mascaraCPF = new MaskFormatter("###.###.###-##");
            mascaraDataNascimento = new MaskFormatter("##/##/####");
        } catch (ParseException ex) {
            Logger.getLogger(JDlgUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        cpf_tto.setFormatterFactory(new DefaultFormatterFactory(mascaraCPF));
        dataNascimento_tto.setFormatterFactory(new DefaultFormatterFactory(mascaraDataNascimento));

    }

    /* public UsuariosTto viewBean() {
        UsuariosTto usuarios = new UsuariosTto();
        int id = Integer.parseInt(idusuarios_tto.getText());
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        try {
            usuarios.setDataNascimentoTto(formato.parse(dataNascimento_tto.getText()));
        } catch (ParseException ex) {
            System.out.println("Erro:" + ex.getMessage());
        }
        usuarios.setIdusuariosTto(Util.strInt(idusuarios_tto.getText()));
        usuarios.setNomeTto(nome_tto.getText());
        usuarios.setNicknameTto(nickname_tto.getText());
        usuarios.setCpfTto(cpf_tto.getText());       
        usuarios.setSenhaTto(senha_tto.getText());
        usuarios.setNivelTto(nivel_tto.getSelectedIndex());
        if (ativo_tto.isSelected() == true) {
            usuarios.setAtivoTto("S");
        } else {
            usuarios.setAtivoTto("N");
        }
        return usuarios;
    }

    public void beanView(UsuariosTto usuarios) {
        String id = String.valueOf(usuarios.getIdusuariosTto());
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");

        dataNascimento_tto.setText(formato.format(usuarios.getDataNascimentoTto()));
        idusuarios_tto.setText(id);
        nome_tto.setText(usuarios.getNomeTto());
        nickname_tto.setText(usuarios.getNicknameTto());
        cpf_tto.setText(usuarios.getCpfTto());
        senha_tto.setText(usuarios.getSenhaTto());
        nivel_tto.setSelectedIndex(usuarios.getNivelTto());
        if (usuarios.getAtivoTto().equals("S") == true) {
            ativo_tto.setSelected(true);
        } else {
            ativo_tto.setSelected(false);
        }

    }
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        idusuarios_tto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nome_tto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cpf_tto = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        nickname_tto = new javax.swing.JTextField();
        dataNascimento_tto = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        senha_tto = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        ativo_tto = new javax.swing.JCheckBox();
        nivel_tto = new javax.swing.JComboBox<>();
        jBtnAlterar = new javax.swing.JButton();
        jBtnIncluir = new javax.swing.JButton();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jBtnPesquisar = new javax.swing.JButton();

        jButton4.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Código");

        idusuarios_tto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                idusuarios_ttoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                idusuarios_ttoFocusLost(evt);
            }
        });

        jLabel3.setText("Nome");

        nome_tto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nome_ttoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nome_ttoFocusLost(evt);
            }
        });

        jLabel4.setText("CPF");

        cpf_tto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cpf_ttoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cpf_ttoFocusLost(evt);
            }
        });

        jLabel5.setText("Apelido");

        nickname_tto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nickname_ttoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nickname_ttoFocusLost(evt);
            }
        });

        dataNascimento_tto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dataNascimento_ttoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dataNascimento_ttoFocusLost(evt);
            }
        });

        jLabel6.setText("Data de nascimento");

        jLabel7.setText("Senha");

        senha_tto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                senha_ttoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                senha_ttoFocusLost(evt);
            }
        });
        senha_tto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senha_ttoActionPerformed(evt);
            }
        });

        jLabel8.setText("Nível");

        ativo_tto.setText("Ativo");
        ativo_tto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ativo_ttoActionPerformed(evt);
            }
        });

        nivel_tto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Usuário" }));
        nivel_tto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nivel_ttoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nivel_ttoFocusLost(evt);
            }
        });

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir_1.png"))); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gravar_1.png"))); // NOI18N
        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar_1.png"))); // NOI18N
        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jBtnIncluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnExcluir)
                                .addGap(6, 6, 6)
                                .addComponent(jBtnConfirmar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnPesquisar)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(idusuarios_tto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                .addComponent(nome_tto, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nickname_tto, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel7)
                            .addComponent(senha_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(dataNascimento_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nivel_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ativo_tto))
                            .addComponent(jLabel4)
                            .addComponent(cpf_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(170, 170, 170))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(idusuarios_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nome_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nickname_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataNascimento_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nivel_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ativo_tto))))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpf_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(senha_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnIncluir)
                    .addComponent(jBtnConfirmar)
                    .addComponent(jBtnExcluir)
                    .addComponent(jBtnCancelar)
                    .addComponent(jBtnPesquisar)
                    .addComponent(jBtnAlterar))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
        // TODO add your handling code here:
        /* UsuariosTto usuarios = viewBean(); */
        Usuarios_DAO usuarios_DAO = new Usuarios_DAO();

        Util.limparCampos(idusuarios_tto, dataNascimento_tto, nome_tto, nickname_tto, senha_tto, nivel_tto, ativo_tto, cpf_tto, jBtnIncluir,
                jBtnCancelar, jBtnExcluir, jBtnPesquisar, jBtnConfirmar, jBtnAlterar);

        Util.habilitar(true, idusuarios_tto, dataNascimento_tto, nome_tto, nickname_tto, senha_tto, nivel_tto, ativo_tto, cpf_tto, jBtnIncluir,
                jBtnCancelar, jBtnExcluir, jBtnPesquisar, jBtnConfirmar, jBtnAlterar);
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        // TODO add your handling code here:
        incluindo = true;
        Util.limparCampos(idusuarios_tto, dataNascimento_tto, nome_tto, nickname_tto, senha_tto, nivel_tto, ativo_tto, cpf_tto, jBtnIncluir,
                jBtnCancelar, jBtnExcluir, jBtnPesquisar, jBtnConfirmar, jBtnAlterar);

        Util.habilitar(true, idusuarios_tto, dataNascimento_tto, nome_tto, nickname_tto, senha_tto, nivel_tto, ativo_tto, cpf_tto, jBtnIncluir,
                jBtnCancelar, jBtnExcluir, jBtnPesquisar, jBtnConfirmar, jBtnAlterar);
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, idusuarios_tto, dataNascimento_tto, nome_tto, nickname_tto, senha_tto, nivel_tto, ativo_tto, cpf_tto, jBtnIncluir,
                jBtnCancelar, jBtnExcluir, jBtnPesquisar, jBtnConfirmar, jBtnAlterar);
        Util.limparCampos(idusuarios_tto, dataNascimento_tto, nome_tto, nickname_tto, senha_tto, nivel_tto, ativo_tto, cpf_tto, jBtnIncluir,
                jBtnCancelar, jBtnExcluir, jBtnPesquisar, jBtnConfirmar, jBtnAlterar);
        incluindo = false;
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        // TODO add your handling code here:
        if (Util.perguntar("Deseja excluir o usuário?") == true) {
        }
        Util.limparCampos(idusuarios_tto, dataNascimento_tto, nome_tto, nickname_tto, senha_tto, nivel_tto, ativo_tto, cpf_tto, jBtnIncluir,
                jBtnCancelar, jBtnExcluir, jBtnPesquisar, jBtnConfirmar, jBtnAlterar);

        Util.habilitar(false, idusuarios_tto, dataNascimento_tto, nome_tto, nickname_tto, senha_tto, nivel_tto, ativo_tto, cpf_tto, jBtnIncluir,
                jBtnCancelar, jBtnExcluir, jBtnPesquisar, jBtnConfirmar, jBtnAlterar);
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        Util.limparCampos(idusuarios_tto, dataNascimento_tto, nome_tto, nickname_tto, senha_tto, nivel_tto, ativo_tto, cpf_tto, jBtnIncluir,
                jBtnCancelar, jBtnExcluir, jBtnPesquisar, jBtnConfirmar, jBtnAlterar);

        Util.habilitar(false, idusuarios_tto, dataNascimento_tto, nome_tto, nickname_tto, senha_tto, nivel_tto, ativo_tto, cpf_tto, jBtnIncluir,
                jBtnCancelar, jBtnExcluir, jBtnPesquisar, jBtnConfirmar, jBtnAlterar);
        JOptionPane.showMessageDialog(null, "Cancelamento concluido");
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
        // TODO add your handling code here:
        /* String resp = JOptionPane.showInputDialog(null, "Entre com o código (PK)",
                "Pesquisar", 2);
        int id = Integer.parseInt(resp);
        //transformou string em inteiro

        Usuarios_DAO usuario_DAO = new Usuarios_DAO();
        Usuarios usuarios = (Usuarios) usuario_DAO.list(id);
        //retorna um bean e mostra na tela
        beanView(usuarios);*/
        JDlgUsuariosPesquisa jDlgUsuariosPesquisa = new JDlgUsuariosPesquisa(null, true);
        jDlgUsuariosPesquisa.setTelaAnterior(this);
        jDlgUsuariosPesquisa.setVisible(true);

    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void nome_ttoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nome_ttoFocusGained
        // TODO add your handling code here:
        nome_tto.setBackground(Color.yellow);

    }//GEN-LAST:event_nome_ttoFocusGained

    private void nome_ttoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nome_ttoFocusLost
        // TODO add your handling code here:
        nome_tto.setBackground(Color.white);
    }//GEN-LAST:event_nome_ttoFocusLost

    private void idusuarios_ttoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idusuarios_ttoFocusGained
        // TODO add your handling code here:
        idusuarios_tto.setBackground(Color.yellow);
    }//GEN-LAST:event_idusuarios_ttoFocusGained

    private void idusuarios_ttoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idusuarios_ttoFocusLost
        // TODO add your handling code here:
        idusuarios_tto.setBackground(Color.white);
    }//GEN-LAST:event_idusuarios_ttoFocusLost

    private void nickname_ttoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nickname_ttoFocusGained
        // TODO add your handling code here:
        nickname_tto.setBackground(Color.yellow);
    }//GEN-LAST:event_nickname_ttoFocusGained

    private void nickname_ttoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nickname_ttoFocusLost
        // TODO add your handling code here:
        nickname_tto.setBackground(Color.white);
    }//GEN-LAST:event_nickname_ttoFocusLost

    private void cpf_ttoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpf_ttoFocusGained
        // TODO add your handling code here:
        cpf_tto.setBackground(Color.yellow);
    }//GEN-LAST:event_cpf_ttoFocusGained

    private void cpf_ttoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpf_ttoFocusLost
        // TODO add your handling code here:
        cpf_tto.setBackground(Color.white);
    }//GEN-LAST:event_cpf_ttoFocusLost

    private void dataNascimento_ttoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataNascimento_ttoFocusGained
        // TODO add your handling code here:
        dataNascimento_tto.setBackground(Color.yellow);
    }//GEN-LAST:event_dataNascimento_ttoFocusGained

    private void dataNascimento_ttoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataNascimento_ttoFocusLost
        // TODO add your handling code here:
        dataNascimento_tto.setBackground(Color.white);
    }//GEN-LAST:event_dataNascimento_ttoFocusLost

    private void senha_ttoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_senha_ttoFocusGained
        // TODO add your handling code here:
        senha_tto.setBackground(Color.yellow);
    }//GEN-LAST:event_senha_ttoFocusGained

    private void senha_ttoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_senha_ttoFocusLost
        // TODO add your handling code here:
        senha_tto.setBackground(Color.white);
    }//GEN-LAST:event_senha_ttoFocusLost

    private void nivel_ttoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nivel_ttoFocusGained
        // TODO add your handling code here:
        nivel_tto.setBackground(Color.yellow);
    }//GEN-LAST:event_nivel_ttoFocusGained

    private void nivel_ttoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nivel_ttoFocusLost
        // TODO add your handling code here:
        nivel_tto.setBackground(Color.white);
    }//GEN-LAST:event_nivel_ttoFocusLost

    private void ativo_ttoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ativo_ttoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ativo_ttoActionPerformed

    private void senha_ttoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senha_ttoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senha_ttoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgUsuarios dialog = new JDlgUsuarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ativo_tto;
    private javax.swing.JFormattedTextField cpf_tto;
    private javax.swing.JFormattedTextField dataNascimento_tto;
    private javax.swing.JTextField idusuarios_tto;
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nickname_tto;
    private javax.swing.JComboBox<String> nivel_tto;
    private javax.swing.JTextField nome_tto;
    private javax.swing.JPasswordField senha_tto;
    // End of variables declaration//GEN-END:variables
}
