/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.FuncionariosTto;
import dao.Funcionarios_DAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import tools.Util;

/**
 *
 * @author TATY
 */
public class JDlgFuncionariosNovoIA extends javax.swing.JDialog {

    FuncionariosTto funcionariosTto;
    Funcionarios_DAO funcionarios_DAO;
    MaskFormatter mascaraCPF, mascaraDataNascimento, mascaraTelefone, mascaraCEP, mascaraCep, mascaraCelular;

    /**
     * Creates new form JDlgFuncionariosNovoIA
     */
    public JDlgFuncionariosNovoIA(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Inclusão de Funcionários");
        setLocationRelativeTo(null);
        funcionarios_DAO = new Funcionarios_DAO();
        
    }

    public FuncionariosTto viewBean() {
        funcionariosTto = new FuncionariosTto();
        funcionariosTto.setIdfuncionariosTto(Util.strInt(codigo_tto.getText()));
        funcionariosTto.setNomeTto(nome_tto.getText());
        funcionariosTto.setCpfTto(cpf_tto.getText());
        funcionariosTto.setEmailTto(email_tto.getText());
        funcionariosTto.setTelefoneTto(telefone_tto.getText());
        funcionariosTto.setEmailReservaTto(emailReserva_tto.getText());
        funcionariosTto.setDataNascimentoTto(Util.strDate(dataNascimento_tto.getText()));
        funcionariosTto.setCelularTto(celular_tto.getText());
        funcionariosTto.setBairroTto(bairro_tto.getText());
        funcionariosTto.setCidadeTto(cidade_tto.getText());
        funcionariosTto.setPaisTto(pais_tto.getText());
        funcionariosTto.setCepTto(cep_tto.getText());
        funcionariosTto.setEnderecoTto(endereco_tto.getText());
        funcionariosTto.setSexoTto(sexo_tto.getSelectedIndex());
        funcionariosTto.setAtivoTto(ativo_tto.getText());
        funcionariosTto.setCarteiratrabalhoTto(carteiraTrabalho_tto.getText());

        return funcionariosTto;

    }

    public void beanView(FuncionariosTto funcionariosTto) {
        codigo_tto.setText(Util.intStr(funcionariosTto.getIdfuncionariosTto()));
        nome_tto.setText(funcionariosTto.getNomeTto());
        cpf_tto.setText(funcionariosTto.getCpfTto());
        email_tto.setText(funcionariosTto.getEmailTto());
        telefone_tto.setText(funcionariosTto.getTelefoneTto());
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        dataNascimento_tto.setText(formato.format(funcionariosTto.getDataNascimentoTto()));
        celular_tto.setText(funcionariosTto.getCelularTto());
        bairro_tto.setText(funcionariosTto.getBairroTto());
        cidade_tto.setText(funcionariosTto.getCidadeTto());
        pais_tto.setText(funcionariosTto.getPaisTto());
        cep_tto.setText(funcionariosTto.getCepTto());
        endereco_tto.setText(funcionariosTto.getEnderecoTto());
        sexo_tto.setToolTipText(Util.intStr(funcionariosTto.getSexoTto()));
        ativo_tto.setText(funcionariosTto.getAtivoTto());
        carteiraTrabalho_tto.setText(funcionariosTto.getCarteiratrabalhoTto());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBtnOk = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nome_tto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        celular_tto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        email_tto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        emailReserva_tto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cpf_tto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dataNascimento_tto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        carteiraTrabalho_tto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        bairro_tto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cidade_tto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        pais_tto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cep_tto = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        telefone_tto = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        endereco_tto = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        codigo_tto = new javax.swing.JTextField();
        sexo_tto = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        ativo_tto = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBtnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok_1.png"))); // NOI18N
        jBtnOk.setText("OK");
        jBtnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOkActionPerformed(evt);
            }
        });

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar_1.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnOk)
                .addGap(33, 33, 33)
                .addComponent(jBtnCancelar)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnOk)
                    .addComponent(jBtnCancelar))
                .addContainerGap())
        );

        jLabel1.setText("Nome");

        nome_tto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_ttoActionPerformed(evt);
            }
        });

        jLabel2.setText("Celular");

        celular_tto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celular_ttoActionPerformed(evt);
            }
        });

        jLabel3.setText("Email");

        email_tto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_ttoActionPerformed(evt);
            }
        });

        jLabel4.setText("Email Reserva");

        emailReserva_tto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailReserva_ttoActionPerformed(evt);
            }
        });

        jLabel5.setText("Cpf");

        cpf_tto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpf_ttoActionPerformed(evt);
            }
        });

        jLabel6.setText("Data de Nascimento");

        dataNascimento_tto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataNascimento_ttoActionPerformed(evt);
            }
        });

        jLabel7.setText("Carteira de Trabalho");

        carteiraTrabalho_tto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carteiraTrabalho_ttoActionPerformed(evt);
            }
        });

        jLabel8.setText("Bairro");

        bairro_tto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bairro_ttoActionPerformed(evt);
            }
        });

        jLabel9.setText("Cidade");

        cidade_tto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidade_ttoActionPerformed(evt);
            }
        });

        jLabel10.setText("País");

        pais_tto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pais_ttoActionPerformed(evt);
            }
        });

        jLabel11.setText("Cep");

        cep_tto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cep_ttoActionPerformed(evt);
            }
        });

        jLabel12.setText("Telefone");

        telefone_tto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefone_ttoActionPerformed(evt);
            }
        });

        jLabel13.setText("Endereço");

        endereco_tto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endereco_ttoActionPerformed(evt);
            }
        });

        jLabel14.setText("Código");

        codigo_tto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigo_ttoActionPerformed(evt);
            }
        });

        sexo_tto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel15.setText("Sexo");

        ativo_tto.setText("Ativo");
        ativo_tto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ativo_ttoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(nome_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(email_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(emailReserva_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cpf_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(dataNascimento_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(celular_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(pais_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(cidade_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(bairro_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(carteiraTrabalho_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(cep_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(telefone_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(endereco_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(codigo_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sexo_tto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ativo_tto)))
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(nome_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(celular_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cep_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(email_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(carteiraTrabalho_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telefone_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailReserva_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bairro_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(endereco_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpf_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cidade_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codigo_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataNascimento_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pais_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sexo_tto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ativo_tto))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nome_ttoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_ttoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_ttoActionPerformed

    private void celular_ttoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celular_ttoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_celular_ttoActionPerformed

    private void email_ttoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_ttoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_ttoActionPerformed

    private void emailReserva_ttoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailReserva_ttoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailReserva_ttoActionPerformed

    private void cpf_ttoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpf_ttoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpf_ttoActionPerformed

    private void dataNascimento_ttoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataNascimento_ttoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataNascimento_ttoActionPerformed

    private void carteiraTrabalho_ttoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carteiraTrabalho_ttoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carteiraTrabalho_ttoActionPerformed

    private void bairro_ttoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bairro_ttoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bairro_ttoActionPerformed

    private void cidade_ttoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidade_ttoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidade_ttoActionPerformed

    private void pais_ttoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pais_ttoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pais_ttoActionPerformed

    private void cep_ttoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cep_ttoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cep_ttoActionPerformed

    private void telefone_ttoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefone_ttoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefone_ttoActionPerformed

    private void endereco_ttoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endereco_ttoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endereco_ttoActionPerformed

    private void codigo_ttoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigo_ttoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigo_ttoActionPerformed

    private void ativo_ttoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ativo_ttoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ativo_ttoActionPerformed

    private void jBtnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOkActionPerformed
        // TODO add your handling code here:
        setVisible(false);

        funcionariosTto = viewBean();
        funcionarios_DAO = new Funcionarios_DAO();
        funcionarios_DAO.insert(funcionariosTto);

        Util.limparCampos();
    }//GEN-LAST:event_jBtnOkActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgFuncionariosNovoIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgFuncionariosNovoIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgFuncionariosNovoIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgFuncionariosNovoIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgFuncionariosNovoIA dialog = new JDlgFuncionariosNovoIA(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ativo_tto;
    private javax.swing.JTextField bairro_tto;
    private javax.swing.JTextField carteiraTrabalho_tto;
    private javax.swing.JTextField celular_tto;
    private javax.swing.JTextField cep_tto;
    private javax.swing.JTextField cidade_tto;
    private javax.swing.JTextField codigo_tto;
    private javax.swing.JTextField cpf_tto;
    private javax.swing.JTextField dataNascimento_tto;
    private javax.swing.JTextField emailReserva_tto;
    private javax.swing.JTextField email_tto;
    private javax.swing.JTextField endereco_tto;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nome_tto;
    private javax.swing.JTextField pais_tto;
    private javax.swing.JComboBox<String> sexo_tto;
    private javax.swing.JTextField telefone_tto;
    // End of variables declaration//GEN-END:variables
}
