/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.FornecedoresTto;
import dao.Fornecedores_DAO;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import tools.Util;

/**
 *
 * @author User
 */
public class JDlgFornecedores extends javax.swing.JDialog {

    private boolean incluindo;
    MaskFormatter mascaraTelefone, mascaraCnpj;

    /**
     * Creates new form JDlgFornecedores
     */
    public JDlgFornecedores(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Fornecedores");
        setLocationRelativeTo(null);
        try {
            mascaraTelefone = new MaskFormatter("(##)#########");
            mascaraCnpj = new MaskFormatter("##.###.###/####-##");

        } catch (ParseException ex) {
            Logger.getLogger(JDlgFornecedores.class.getName()).log(Level.SEVERE, null, ex);
        }
        telefone_tto.setFormatterFactory(new DefaultFormatterFactory(mascaraTelefone));
        cnpj_tto.setFormatterFactory(new DefaultFormatterFactory(mascaraCnpj));
    }

    /*
    public Fornecedores viewBean(){
        Fornecedores fornecedores = new Fornecedores();
        int id = Integer.parseInt(jTxtCodigo.getText());
        //transforma de string para inteiro
        
        fornecedores.setIdfornecedor(id);
        fornecedores.setNome(jTxtNome.getText());
        fornecedores.setCnpj(jFmtCnpj.getText());
        fornecedores.setEmail(jTxtEmail.getText());
        fornecedores.setEnderecocompleto(jTxtEndereco.getText());
        fornecedores.setTelefone(jFmtTelefone.getText());
        return fornecedores;
    }
    
    public void beanView(Fornecedores fornecedores){
        String id = String.valueOf(fornecedores.getIdfornecedor());
        //transforma de inteiro pra string
        
        jTxtCodigo.setText(id);
        jTxtNome.setText(fornecedores.getNome());
        jFmtCnpj.setText(fornecedores.getCnpj());
        jTxtEmail.setText(fornecedores.getEmail());
        jTxtEndereco.setText(fornecedores.getEnderecocompleto());
        jFmtTelefone.setText(fornecedores.getTelefone());
      
    }

    
    
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nome_tto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        email_tto = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        telefone_tto = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        cnpj_tto = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        enderecoCompleto_tto = new javax.swing.JTextField();
        jBtnIncluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jBtnPesquisar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        idfornecedores_tto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nome");

        jLabel2.setText("Email");

        email_tto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_ttoActionPerformed(evt);
            }
        });

        jLabel13.setText("Telefone");

        telefone_tto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefone_ttoActionPerformed(evt);
            }
        });

        jLabel7.setText("Cnpj");

        jLabel15.setText("Endereço Completo");

        enderecoCompleto_tto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enderecoCompleto_ttoActionPerformed(evt);
            }
        });

        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir_1.png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gravar.png"))); // NOI18N
        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        jLabel3.setText("Código");

        idfornecedores_tto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                idfornecedores_ttoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                idfornecedores_ttoFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(nome_tto, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(email_tto))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enderecoCompleto_tto)
                            .addComponent(idfornecedores_tto))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(140, 140, 140))
                    .addComponent(telefone_tto)
                    .addComponent(jLabel7)
                    .addComponent(cnpj_tto))
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnPesquisar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nome_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(email_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(enderecoCompleto_tto)
                                    .addComponent(telefone_tto, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cnpj_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idfornecedores_tto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnIncluir)
                    .addComponent(jBtnAlterar)
                    .addComponent(jBtnExcluir)
                    .addComponent(jBtnConfirmar)
                    .addComponent(jBtnCancelar)
                    .addComponent(jBtnPesquisar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void email_ttoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_ttoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_ttoActionPerformed

    private void telefone_ttoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefone_ttoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefone_ttoActionPerformed

    private void enderecoCompleto_ttoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enderecoCompleto_ttoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enderecoCompleto_ttoActionPerformed

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        // TODO add your handling code here:
        Util.limparCampos(idfornecedores_tto, nome_tto, email_tto, enderecoCompleto_tto, telefone_tto, cnpj_tto,
                jBtnIncluir, jBtnCancelar, jBtnExcluir, jBtnPesquisar, jBtnConfirmar, jBtnAlterar);

        Util.habilitar(true, idfornecedores_tto, nome_tto, email_tto, enderecoCompleto_tto, telefone_tto, cnpj_tto,
                jBtnIncluir, jBtnCancelar, jBtnExcluir, jBtnPesquisar, jBtnConfirmar, jBtnAlterar);

    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
        // TODO add your handling code here:
        Util.limparCampos(idfornecedores_tto, nome_tto, email_tto, enderecoCompleto_tto, telefone_tto, cnpj_tto,
                jBtnIncluir, jBtnCancelar, jBtnExcluir, jBtnPesquisar, jBtnConfirmar, jBtnAlterar);

        Util.habilitar(true, idfornecedores_tto, nome_tto, email_tto, enderecoCompleto_tto, telefone_tto, cnpj_tto,
                jBtnIncluir, jBtnCancelar, jBtnExcluir, jBtnPesquisar, jBtnConfirmar, jBtnAlterar);
        
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        // TODO add your handling code here:
        if (Util.perguntar("Deseja excluir o fornecedor?") == true) {
        }
        
        Util.limparCampos(idfornecedores_tto, nome_tto, email_tto, enderecoCompleto_tto, telefone_tto, cnpj_tto,
                jBtnIncluir, jBtnCancelar, jBtnExcluir, jBtnPesquisar, jBtnConfirmar, jBtnAlterar);

        Util.habilitar(false, idfornecedores_tto, nome_tto, email_tto, enderecoCompleto_tto, telefone_tto, cnpj_tto,
                jBtnIncluir, jBtnCancelar, jBtnExcluir, jBtnPesquisar, jBtnConfirmar, jBtnAlterar);
        
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
        // TODO add your handling code here:
        //Fornecedores fornecedores = viewBean();
        Fornecedores_DAO fornecedores_DAO = new Fornecedores_DAO();

        Util.limparCampos(idfornecedores_tto, nome_tto, email_tto, enderecoCompleto_tto, telefone_tto, cnpj_tto,
                jBtnIncluir, jBtnCancelar, jBtnExcluir, jBtnPesquisar, jBtnConfirmar, jBtnAlterar);

        Util.habilitar(true, idfornecedores_tto, nome_tto, email_tto, enderecoCompleto_tto, telefone_tto, cnpj_tto,
                jBtnIncluir, jBtnCancelar, jBtnExcluir, jBtnPesquisar, jBtnConfirmar, jBtnAlterar);

    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Cancelamento concluido");
        Util.limparCampos(idfornecedores_tto, nome_tto, email_tto, enderecoCompleto_tto, telefone_tto, cnpj_tto,
                jBtnIncluir, jBtnCancelar, jBtnExcluir, jBtnPesquisar, jBtnConfirmar, jBtnAlterar);

        Util.habilitar(false, idfornecedores_tto, nome_tto, email_tto, enderecoCompleto_tto, telefone_tto, cnpj_tto,
                jBtnIncluir, jBtnCancelar, jBtnExcluir, jBtnPesquisar, jBtnConfirmar, jBtnAlterar);

    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
        // TODO add your handling code here:
        /*  String resp = JOptionPane.showInputDialog(null, "Entre com o código (PK)",
                "Pesquisar", 2);
        int id = Integer.parseInt(resp);
        //transformou string em inteiro
        
         Fornecedores_DAO fornecedores_DAO = new Fornecedores_DAO();
         Fornecedores fornecedores= (Fornecedores)fornecedores_DAO.list(id);
        //retorna um bean e mostra na tela
        beanView(fornecedores);*/
        JDlgFornecedoresPesquisa jDlgFornecedoresPesquisa = new JDlgFornecedoresPesquisa(null, true);
        jDlgFornecedoresPesquisa.setTelaAnterior(this);
        jDlgFornecedoresPesquisa.setVisible(true);
        
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void idfornecedores_ttoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idfornecedores_ttoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_idfornecedores_ttoFocusGained

    private void idfornecedores_ttoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idfornecedores_ttoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_idfornecedores_ttoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgFornecedores dialog = new JDlgFornecedores(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField cnpj_tto;
    private javax.swing.JTextField email_tto;
    private javax.swing.JTextField enderecoCompleto_tto;
    private javax.swing.JTextField idfornecedores_tto;
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nome_tto;
    private javax.swing.JFormattedTextField telefone_tto;
    // End of variables declaration//GEN-END:variables
}
