package bean;
// Generated Sep 22, 2023 8:43:48 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ComprasProdutosTto generated by hbm2java
 */
@Entity
@Table(name="compras_produtos_tto"
    ,catalog="db_tatiana_oseko"
)
public class ComprasProdutosTto  implements java.io.Serializable {


     private int idcomprasProdutosTto;
     private ComprasTto comprasTto;
     private ProdutosTto produtosTto;
     private String quantidadeTto;
     private double valorUnitarioTto;

    public ComprasProdutosTto() {
    }

    public ComprasProdutosTto(int idcomprasProdutosTto, ComprasTto comprasTto, ProdutosTto produtosTto, String quantidadeTto, double valorUnitarioTto) {
       this.idcomprasProdutosTto = idcomprasProdutosTto;
       this.comprasTto = comprasTto;
       this.produtosTto = produtosTto;
       this.quantidadeTto = quantidadeTto;
       this.valorUnitarioTto = valorUnitarioTto;
    }
   
     @Id 

    
    @Column(name="idcompras_produtos_tto", unique=true, nullable=false)
    public int getIdcomprasProdutosTto() {
        return this.idcomprasProdutosTto;
    }
    
    public void setIdcomprasProdutosTto(int idcomprasProdutosTto) {
        this.idcomprasProdutosTto = idcomprasProdutosTto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="compra_tto", nullable=false)
    public ComprasTto getComprasTto() {
        return this.comprasTto;
    }
    
    public void setComprasTto(ComprasTto comprasTto) {
        this.comprasTto = comprasTto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="produto_tto", nullable=false)
    public ProdutosTto getProdutosTto() {
        return this.produtosTto;
    }
    
    public void setProdutosTto(ProdutosTto produtosTto) {
        this.produtosTto = produtosTto;
    }

    
    @Column(name="quantidade_tto", nullable=false, length=45)
    public String getQuantidadeTto() {
        return this.quantidadeTto;
    }
    
    public void setQuantidadeTto(String quantidadeTto) {
        this.quantidadeTto = quantidadeTto;
    }

    
    @Column(name="valorUnitario_tto", nullable=false, precision=10)
    public double getValorUnitarioTto() {
        return this.valorUnitarioTto;
    }
    
    public void setValorUnitarioTto(double valorUnitarioTto) {
        this.valorUnitarioTto = valorUnitarioTto;
    }




}


