package bean;
// Generated Sep 22, 2023 8:43:48 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ComprasTto generated by hbm2java
 */
@Entity
@Table(name="compras_tto"
    ,catalog="db_tatiana_oseko"
)
public class ComprasTto  implements java.io.Serializable {


     private int idcomprasTto;
     private FornecedoresTto fornecedoresTto;
     private FuncionariosTto funcionariosTto;
     private Date dataTto;
     private double totalTto;

    public ComprasTto() {
    }

	
    public ComprasTto(int idcomprasTto, FornecedoresTto fornecedoresTto, FuncionariosTto funcionariosTto, Date dataTto, double totalTto) {
        this.idcomprasTto = idcomprasTto;
        this.fornecedoresTto = fornecedoresTto;
        this.funcionariosTto = funcionariosTto;
        this.dataTto = dataTto;
        this.totalTto = totalTto;
    }
   
     @Id 

    
    @Column(name="idcompras_tto", unique=true, nullable=false)
    public int getIdcomprasTto() {
        return this.idcomprasTto;
    }
    
    public void setIdcomprasTto(int idcomprasTto) {
        this.idcomprasTto = idcomprasTto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fornecedor_tto", nullable=false)
    public FornecedoresTto getFornecedoresTto() {
        return this.fornecedoresTto;
    }
    
    public void setFornecedoresTto(FornecedoresTto fornecedoresTto) {
        this.fornecedoresTto = fornecedoresTto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="funcionario_tto", nullable=false)
    public FuncionariosTto getFuncionariosTto() {
        return this.funcionariosTto;
    }
    
    public void setFuncionariosTto(FuncionariosTto funcionariosTto) {
        this.funcionariosTto = funcionariosTto;
    }

    
    @Column(name="data_tto", nullable=false, length=45)
    public Date getDataTto() {
        return this.dataTto;
    }
    
    public void setDataTto(Date dataTto) {
        this.dataTto = dataTto;
    }

    
    @Column(name="total_tto", nullable=false, precision=10)
    public double getTotalTto() {
        return this.totalTto;
    }
    
    public void setTotalTto(double totalTto) {
        this.totalTto = totalTto;
    }
}


