package bean;
// Generated Sep 16, 2023 5:55:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ComprasTto generated by hbm2java
 */
@Entity
@Table(name="compras_tto"
    ,catalog="db_tatiana_oseko"
)
public class ComprasTto  implements java.io.Serializable {


     private int idcomprasTto;
     private FornecedoresTto fornecedoresTto;
     private FuncionariosTto funcionariosTto;
     private String dataTto;
     private Double totalTto;
     private Set comprasProdutosTtos = new HashSet(0);

    public ComprasTto() {
    }

	
    public ComprasTto(int idcomprasTto, FornecedoresTto fornecedoresTto, FuncionariosTto funcionariosTto, String dataTto, Double totalTto) {
        this.idcomprasTto = idcomprasTto;
        this.fornecedoresTto = fornecedoresTto;
        this.funcionariosTto = funcionariosTto;
        this.dataTto = dataTto;
        this.totalTto = totalTto;
    }
    public ComprasTto(int idcomprasTto, FornecedoresTto fornecedoresTto, FuncionariosTto funcionariosTto, String dataTto, Double totalTto, Set comprasProdutosTtos) {
       this.idcomprasTto = idcomprasTto;
       this.fornecedoresTto = fornecedoresTto;
       this.funcionariosTto = funcionariosTto;
       this.dataTto = dataTto;
       this.totalTto = totalTto;
       this.comprasProdutosTtos = comprasProdutosTtos;
    }
   
     @Id 

    
    @Column(name="idcompras_tto", unique=true, nullable=false)
    public int getIdcomprasTto() {
        return this.idcomprasTto;
    }
    
    public void setIdcomprasTto(int idcomprasTto) {
        this.idcomprasTto = idcomprasTto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fornecedor_tto", nullable=false)
    public FornecedoresTto getFornecedoresTto() {
        return this.fornecedoresTto;
    }
    
    public void setFornecedoresTto(FornecedoresTto fornecedoresTto) {
        this.fornecedoresTto = fornecedoresTto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="funcionario_tto", nullable=false)
    public FuncionariosTto getFuncionariosTto() {
        return this.funcionariosTto;
    }
    
    public void setFuncionariosTto(FuncionariosTto funcionariosTto) {
        this.funcionariosTto = funcionariosTto;
    }

    
    @Column(name="data_tto", nullable=false, length=45)
    public String getDataTto() {
        return this.dataTto;
    }
    
    public void setDataTto(String dataTto) {
        this.dataTto = dataTto;
    }

    
    @Column(name="total_tto", nullable=false, precision=10)
    public Double getTotalTto() {
        return this.totalTto;
    }
    
    public void setTotalTto(Double totalTto) {
        this.totalTto = totalTto;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comprasTto")
    public Set getComprasProdutosTtos() {
        return this.comprasProdutosTtos;
    }
    
    public void setComprasProdutosTtos(Set comprasProdutosTtos) {
        this.comprasProdutosTtos = comprasProdutosTtos;
    }




}


