package bean;
// Generated Sep 22, 2023 8:43:48 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FornecedoresTto generated by hbm2java
 */
@Entity
@Table(name="fornecedores_tto"
    ,catalog="db_tatiana_oseko"
)
public class FornecedoresTto  implements java.io.Serializable {


     private int idfornecedoresTto;
     private String nomeTto;
     private String emailTto;
     private String telefoneTto;
     private String cnpjTto;
     private String enderecoCompletoTto;

    public FornecedoresTto() {
    }

	
    public FornecedoresTto(int idfornecedoresTto, String nomeTto, String emailTto, String telefoneTto, String cnpjTto, String enderecoCompletoTto) {
        this.idfornecedoresTto = idfornecedoresTto;
        this.nomeTto = nomeTto;
        this.emailTto = emailTto;
        this.telefoneTto = telefoneTto;
        this.cnpjTto = cnpjTto;
        this.enderecoCompletoTto = enderecoCompletoTto;
    }
   
     @Id 

    
    @Column(name="idfornecedores_tto", unique=true, nullable=false)
    public int getIdfornecedoresTto() {
        return this.idfornecedoresTto;
    }
    
    public void setIdfornecedoresTto(int idfornecedoresTto) {
        this.idfornecedoresTto = idfornecedoresTto;
    }

    
    @Column(name="nome_tto", nullable=false, length=45)
    public String getNomeTto() {
        return this.nomeTto;
    }
    
    public void setNomeTto(String nomeTto) {
        this.nomeTto = nomeTto;
    }

    
    @Column(name="email_tto", nullable=false, length=45)
    public String getEmailTto() {
        return this.emailTto;
    }
    
    public void setEmailTto(String emailTto) {
        this.emailTto = emailTto;
    }

    
    @Column(name="telefone_tto", nullable=false, length=45)
    public String getTelefoneTto() {
        return this.telefoneTto;
    }
    
    public void setTelefoneTto(String telefoneTto) {
        this.telefoneTto = telefoneTto;
    }

    
    @Column(name="cnpj_tto", nullable=false, length=25)
    public String getCnpjTto() {
        return this.cnpjTto;
    }
    
    public void setCnpjTto(String cnpjTto) {
        this.cnpjTto = cnpjTto;
    }

    
    @Column(name="enderecoCompleto_tto", nullable=false, length=250)
    public String getEnderecoCompletoTto() {
        return this.enderecoCompletoTto;
    }
    
    public void setEnderecoCompletoTto(String enderecoCompletoTto) {
        this.enderecoCompletoTto = enderecoCompletoTto;
    }
    
    @Override
    public String toString(){
        return getNomeTto();
    }
    
}


