package bean;
// Generated Sep 16, 2023 5:55:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FornecedoresTto generated by hbm2java
 */
@Entity
@Table(name="fornecedores_tto"
    ,catalog="db_tatiana_oseko"
)
public class FornecedoresTto  implements java.io.Serializable {


     private int idfornecedoresTto;
     private String nomeTto;
     private String emailTto;
     private String telefoneTto;
     private String cnpjTto;
     private String enderecoCompletoTto;
     private Set comprasTtos = new HashSet(0);

    public FornecedoresTto() {
    }

	
    public FornecedoresTto(int idfornecedoresTto, String nomeTto, String emailTto, String telefoneTto, String cnpjTto, String enderecoCompletoTto) {
        this.idfornecedoresTto = idfornecedoresTto;
        this.nomeTto = nomeTto;
        this.emailTto = emailTto;
        this.telefoneTto = telefoneTto;
        this.cnpjTto = cnpjTto;
        this.enderecoCompletoTto = enderecoCompletoTto;
    }
    public FornecedoresTto(int idfornecedoresTto, String nomeTto, String emailTto, String telefoneTto, String cnpjTto, String enderecoCompletoTto, Set comprasTtos) {
       this.idfornecedoresTto = idfornecedoresTto;
       this.nomeTto = nomeTto;
       this.emailTto = emailTto;
       this.telefoneTto = telefoneTto;
       this.cnpjTto = cnpjTto;
       this.enderecoCompletoTto = enderecoCompletoTto;
       this.comprasTtos = comprasTtos;
    }
   
     @Id 

    
    @Column(name="idfornecedores_tto", unique=true, nullable=false)
    public int getIdfornecedoresTto() {
        return this.idfornecedoresTto;
    }
    
    public void setIdfornecedoresTto(int idfornecedoresTto) {
        this.idfornecedoresTto = idfornecedoresTto;
    }

    
    @Column(name="nome_tto", nullable=false, length=45)
    public String getNomeTto() {
        return this.nomeTto;
    }
    
    public void setNomeTto(String nomeTto) {
        this.nomeTto = nomeTto;
    }

    
    @Column(name="email_tto", nullable=false, length=45)
    public String getEmailTto() {
        return this.emailTto;
    }
    
    public void setEmailTto(String emailTto) {
        this.emailTto = emailTto;
    }

    
    @Column(name="telefone_tto", nullable=false, length=45)
    public String getTelefoneTto() {
        return this.telefoneTto;
    }
    
    public void setTelefoneTto(String telefoneTto) {
        this.telefoneTto = telefoneTto;
    }

    
    @Column(name="cnpj_tto", nullable=false, length=25)
    public String getCnpjTto() {
        return this.cnpjTto;
    }
    
    public void setCnpjTto(String cnpjTto) {
        this.cnpjTto = cnpjTto;
    }

    
    @Column(name="enderecoCompleto_tto", nullable=false, length=250)
    public String getEnderecoCompletoTto() {
        return this.enderecoCompletoTto;
    }
    
    public void setEnderecoCompletoTto(String enderecoCompletoTto) {
        this.enderecoCompletoTto = enderecoCompletoTto;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fornecedoresTto")
    public Set getComprasTtos() {
        return this.comprasTtos;
    }
    
    public void setComprasTtos(Set comprasTtos) {
        this.comprasTtos = comprasTtos;
    }




}


