package bean;
// Generated Sep 16, 2023 5:55:13 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FuncionariosTto generated by hbm2java
 */
@Entity
@Table(name="funcionarios_tto"
    ,catalog="db_tatiana_oseko"
)
public class FuncionariosTto  implements java.io.Serializable {


     private int idfuncionariosTto;
     private String nomeTto;
     private String cpfTto;
     private String emailTto;
     private String telefoneTto;
     private String emailReservaTto;
     private Date dataNascimentoTto;
     private String celularTto;
     private String bairroTto;
     private String cidadeTto;
     private String paisTto;
     private String cepTto;
     private String enderecoTto;
     private String sexoTto;
     private String ativoTto;
     private String carteiratrabalhoTto;
     private Set comprasTtos = new HashSet(0);

    public FuncionariosTto() {
    }

	
    public FuncionariosTto(int idfuncionariosTto, String nomeTto, String cpfTto, String emailTto, String telefoneTto, Date dataNascimentoTto, String celularTto, String bairroTto, String cidadeTto, String paisTto, String cepTto, String enderecoTto, String sexoTto, String ativoTto, String carteiratrabalhoTto) {
        this.idfuncionariosTto = idfuncionariosTto;
        this.nomeTto = nomeTto;
        this.cpfTto = cpfTto;
        this.emailTto = emailTto;
        this.telefoneTto = telefoneTto;
        this.dataNascimentoTto = dataNascimentoTto;
        this.celularTto = celularTto;
        this.bairroTto = bairroTto;
        this.cidadeTto = cidadeTto;
        this.paisTto = paisTto;
        this.cepTto = cepTto;
        this.enderecoTto = enderecoTto;
        this.sexoTto = sexoTto;
        this.ativoTto = ativoTto;
        this.carteiratrabalhoTto = carteiratrabalhoTto;
    }
    public FuncionariosTto(int idfuncionariosTto, String nomeTto, String cpfTto, String emailTto, String telefoneTto, String emailReservaTto, Date dataNascimentoTto, String celularTto, String bairroTto, String cidadeTto, String paisTto, String cepTto, String enderecoTto, String sexoTto, String ativoTto, String carteiratrabalhoTto, Set comprasTtos) {
       this.idfuncionariosTto = idfuncionariosTto;
       this.nomeTto = nomeTto;
       this.cpfTto = cpfTto;
       this.emailTto = emailTto;
       this.telefoneTto = telefoneTto;
       this.emailReservaTto = emailReservaTto;
       this.dataNascimentoTto = dataNascimentoTto;
       this.celularTto = celularTto;
       this.bairroTto = bairroTto;
       this.cidadeTto = cidadeTto;
       this.paisTto = paisTto;
       this.cepTto = cepTto;
       this.enderecoTto = enderecoTto;
       this.sexoTto = sexoTto;
       this.ativoTto = ativoTto;
       this.carteiratrabalhoTto = carteiratrabalhoTto;
       this.comprasTtos = comprasTtos;
    }
   
     @Id 

    
    @Column(name="idfuncionarios_tto", unique=true, nullable=false)
    public int getIdfuncionariosTto() {
        return this.idfuncionariosTto;
    }
    
    public void setIdfuncionariosTto(int idfuncionariosTto) {
        this.idfuncionariosTto = idfuncionariosTto;
    }

    
    @Column(name="nome_tto", nullable=false, length=45)
    public String getNomeTto() {
        return this.nomeTto;
    }
    
    public void setNomeTto(String nomeTto) {
        this.nomeTto = nomeTto;
    }

    
    @Column(name="cpf_tto", nullable=false, length=14)
    public String getCpfTto() {
        return this.cpfTto;
    }
    
    public void setCpfTto(String cpfTto) {
        this.cpfTto = cpfTto;
    }

    
    @Column(name="email_tto", nullable=false, length=45)
    public String getEmailTto() {
        return this.emailTto;
    }
    
    public void setEmailTto(String emailTto) {
        this.emailTto = emailTto;
    }

    
    @Column(name="telefone_tto", nullable=false, length=15)
    public String getTelefoneTto() {
        return this.telefoneTto;
    }
    
    public void setTelefoneTto(String telefoneTto) {
        this.telefoneTto = telefoneTto;
    }

    
    @Column(name="emailReserva_tto", length=45)
    public String getEmailReservaTto() {
        return this.emailReservaTto;
    }
    
    public void setEmailReservaTto(String emailReservaTto) {
        this.emailReservaTto = emailReservaTto;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataNascimento_tto", nullable=false, length=10)
    public Date getDataNascimentoTto() {
        return this.dataNascimentoTto;
    }
    
    public void setDataNascimentoTto(Date dataNascimentoTto) {
        this.dataNascimentoTto = dataNascimentoTto;
    }

    
    @Column(name="celular_tto", nullable=false, length=15)
    public String getCelularTto() {
        return this.celularTto;
    }
    
    public void setCelularTto(String celularTto) {
        this.celularTto = celularTto;
    }

    
    @Column(name="bairro_tto", nullable=false, length=45)
    public String getBairroTto() {
        return this.bairroTto;
    }
    
    public void setBairroTto(String bairroTto) {
        this.bairroTto = bairroTto;
    }

    
    @Column(name="cidade_tto", nullable=false, length=45)
    public String getCidadeTto() {
        return this.cidadeTto;
    }
    
    public void setCidadeTto(String cidadeTto) {
        this.cidadeTto = cidadeTto;
    }

    
    @Column(name="pais_tto", nullable=false, length=45)
    public String getPaisTto() {
        return this.paisTto;
    }
    
    public void setPaisTto(String paisTto) {
        this.paisTto = paisTto;
    }

    
    @Column(name="cep_tto", nullable=false, length=45)
    public String getCepTto() {
        return this.cepTto;
    }
    
    public void setCepTto(String cepTto) {
        this.cepTto = cepTto;
    }

    
    @Column(name="endereco_tto", nullable=false, length=45)
    public String getEnderecoTto() {
        return this.enderecoTto;
    }
    
    public void setEnderecoTto(String enderecoTto) {
        this.enderecoTto = enderecoTto;
    }

    
    @Column(name="sexo_tto", nullable=false, length=1)
    public String getSexoTto() {
        return this.sexoTto;
    }
    
    public void setSexoTto(String sexoTto) {
        this.sexoTto = sexoTto;
    }

    
    @Column(name="ativo_tto", nullable=false, length=1)
    public String getAtivoTto() {
        return this.ativoTto;
    }
    
    public void setAtivoTto(String ativoTto) {
        this.ativoTto = ativoTto;
    }

    
    @Column(name="carteiratrabalho_tto", nullable=false, length=45)
    public String getCarteiratrabalhoTto() {
        return this.carteiratrabalhoTto;
    }
    
    public void setCarteiratrabalhoTto(String carteiratrabalhoTto) {
        this.carteiratrabalhoTto = carteiratrabalhoTto;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="funcionariosTto")
    public Set getComprasTtos() {
        return this.comprasTtos;
    }
    
    public void setComprasTtos(Set comprasTtos) {
        this.comprasTtos = comprasTtos;
    }




}


