package bean;
// Generated Sep 22, 2023 8:43:48 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProdutosTto generated by hbm2java
 */
@Entity
@Table(name="produtos_tto"
    ,catalog="db_tatiana_oseko"
)
public class ProdutosTto  implements java.io.Serializable {


     private int idprodutosTto;
     private String nomeTto;
     private String descricaoTto;
     private double valorUnitarioTto;
     private int categoriaTto;

    public ProdutosTto() {
    }

	
    public ProdutosTto(int idprodutosTto, String nomeTto, String descricaoTto, double valorUnitarioTto, int categoriaTto) {
        this.idprodutosTto = idprodutosTto;
        this.nomeTto = nomeTto;
        this.descricaoTto = descricaoTto;
        this.valorUnitarioTto = valorUnitarioTto;
        this.categoriaTto = categoriaTto;
    }
   
     @Id 

    
    @Column(name="idprodutos_tto", unique=true, nullable=false)
    public int getIdprodutosTto() {
        return this.idprodutosTto;
    }
    
    public void setIdprodutosTto(int idprodutosTto) {
        this.idprodutosTto = idprodutosTto;
    }

    
    @Column(name="nome_tto", nullable=false, length=45)
    public String getNomeTto() {
        return this.nomeTto;
    }
    
    public void setNomeTto(String nomeTto) {
        this.nomeTto = nomeTto;
    }

    
    @Column(name="descricao_tto", nullable=false, length=250)
    public String getDescricaoTto() {
        return this.descricaoTto;
    }
    
    public void setDescricaoTto(String descricaoTto) {
        this.descricaoTto = descricaoTto;
    }

    
    @Column(name="valorUnitario_tto", nullable=false, precision=10)
    public double getValorUnitarioTto() {
        return this.valorUnitarioTto;
    }
    
    public void setValorUnitarioTto(double valorUnitarioTto) {
        this.valorUnitarioTto = valorUnitarioTto;
    }
    
    @Column(name="categoria_tto", nullable=false, length=45)
    public int getCategoriaTto() {
        return this.categoriaTto;
    }
    
    public void setCategoriaTto(int categoriaTto) {
        this.categoriaTto = categoriaTto;
    }
        @Override
    public String toString(){
        return getNomeTto();
    }
         @Override
    public boolean equals (Object object){
    if(object instanceof ProdutosTto){
        ProdutosTto produtosTto = (ProdutosTto) object;
    if(this.getIdprodutosTto()==produtosTto.getIdprodutosTto()){
    return true;
    }
    }
    return false;
}
}


