package bean;
// Generated Sep 16, 2023 5:55:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProdutosTto generated by hbm2java
 */
@Entity
@Table(name="produtos_tto"
    ,catalog="db_tatiana_oseko"
)
public class ProdutosTto  implements java.io.Serializable {


     private int idprodutosTto;
     private String nomeTto;
     private String descricaoTto;
     private String valorCompraTto;
     private String valorVendaTto;
     private String categoriaTto;
     private Set comprasProdutosTtos = new HashSet(0);

    public ProdutosTto() {
    }

	
    public ProdutosTto(int idprodutosTto, String nomeTto, String descricaoTto, String valorCompraTto, String valorVendaTto, String categoriaTto) {
        this.idprodutosTto = idprodutosTto;
        this.nomeTto = nomeTto;
        this.descricaoTto = descricaoTto;
        this.valorCompraTto = valorCompraTto;
        this.valorVendaTto = valorVendaTto;
        this.categoriaTto = categoriaTto;
    }
    public ProdutosTto(int idprodutosTto, String nomeTto, String descricaoTto, String valorCompraTto, String valorVendaTto, String categoriaTto, Set comprasProdutosTtos) {
       this.idprodutosTto = idprodutosTto;
       this.nomeTto = nomeTto;
       this.descricaoTto = descricaoTto;
       this.valorCompraTto = valorCompraTto;
       this.valorVendaTto = valorVendaTto;
       this.categoriaTto = categoriaTto;
       this.comprasProdutosTtos = comprasProdutosTtos;
    }
   
     @Id 

    
    @Column(name="idprodutos_tto", unique=true, nullable=false)
    public int getIdprodutosTto() {
        return this.idprodutosTto;
    }
    
    public void setIdprodutosTto(int idprodutosTto) {
        this.idprodutosTto = idprodutosTto;
    }

    
    @Column(name="nome_tto", nullable=false, length=45)
    public String getNomeTto() {
        return this.nomeTto;
    }
    
    public void setNomeTto(String nomeTto) {
        this.nomeTto = nomeTto;
    }

    
    @Column(name="descricao_tto", nullable=false, length=250)
    public String getDescricaoTto() {
        return this.descricaoTto;
    }
    
    public void setDescricaoTto(String descricaoTto) {
        this.descricaoTto = descricaoTto;
    }

    
    @Column(name="valorCompra_tto", nullable=false, length=45)
    public String getValorCompraTto() {
        return this.valorCompraTto;
    }
    
    public void setValorCompraTto(String valorCompraTto) {
        this.valorCompraTto = valorCompraTto;
    }

    
    @Column(name="valorVenda_tto", nullable=false, length=45)
    public String getValorVendaTto() {
        return this.valorVendaTto;
    }
    
    public void setValorVendaTto(String valorVendaTto) {
        this.valorVendaTto = valorVendaTto;
    }

    
    @Column(name="categoria_tto", nullable=false, length=45)
    public String getCategoriaTto() {
        return this.categoriaTto;
    }
    
    public void setCategoriaTto(String categoriaTto) {
        this.categoriaTto = categoriaTto;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="produtosTto")
    public Set getComprasProdutosTtos() {
        return this.comprasProdutosTtos;
    }
    
    public void setComprasProdutosTtos(Set comprasProdutosTtos) {
        this.comprasProdutosTtos = comprasProdutosTtos;
    }




}


