package bean;
// Generated Sep 22, 2023 8:43:48 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UsuariosTto generated by hbm2java
 */
@Entity
@Table(name="usuarios_tto"
    ,catalog="db_tatiana_oseko"
)
public class UsuariosTto  implements java.io.Serializable {


     private int idusuariosTto;
     private String nomeTto;
     private String nicknameTto;
     private String cpfTto;
     private Date dataNascimentoTto;
     private String senhaTto;
     private int nivelTto;
     private String ativoTto;

    public UsuariosTto() {
    }

    public UsuariosTto(int idusuariosTto, String nomeTto, String nicknameTto, String cpfTto, Date dataNascimentoTto, String senhaTto, int nivelTto, String ativoTto) {
       this.idusuariosTto = idusuariosTto;
       this.nomeTto = nomeTto;
       this.nicknameTto = nicknameTto;
       this.cpfTto = cpfTto;
       this.dataNascimentoTto = dataNascimentoTto;
       this.senhaTto = senhaTto;
       this.nivelTto = nivelTto;
       this.ativoTto = ativoTto;
    }
   
     @Id 

    
    @Column(name="idusuarios_tto", unique=true, nullable=false)
    public int getIdusuariosTto() {
        return this.idusuariosTto;
    }
    
    public void setIdusuariosTto(int idusuariosTto) {
        this.idusuariosTto = idusuariosTto;
    }

    
    @Column(name="nome_tto", nullable=false, length=45)
    public String getNomeTto() {
        return this.nomeTto;
    }
    
    public void setNomeTto(String nomeTto) {
        this.nomeTto = nomeTto;
    }

    
    @Column(name="nickname_tto", nullable=false, length=45)
    public String getNicknameTto() {
        return this.nicknameTto;
    }
    
    public void setNicknameTto(String nicknameTto) {
        this.nicknameTto = nicknameTto;
    }

    
    @Column(name="cpf_tto", nullable=false, length=14)
    public String getCpfTto() {
        return this.cpfTto;
    }
    
    public void setCpfTto(String cpfTto) {
        this.cpfTto = cpfTto;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataNascimento_tto", nullable=false, length=10)
    public Date getDataNascimentoTto() {
        return this.dataNascimentoTto;
    }
    
    public void setDataNascimentoTto(Date dataNascimentoTto) {
        this.dataNascimentoTto = dataNascimentoTto;
    }

    
    @Column(name="senha_tto", nullable=false, length=20)
    public String getSenhaTto() {
        return this.senhaTto;
    }
    
    public void setSenhaTto(String senhaTto) {
        this.senhaTto = senhaTto;
    }

    
    @Column(name="nivel_tto", nullable=false)
    public int getNivelTto() {
        return this.nivelTto;
    }
    
    public void setNivelTto(int nivelTto) {
        this.nivelTto = nivelTto;
    }

    
    @Column(name="ativo_tto", nullable=false, length=1)
    public String getAtivoTto() {
        return this.ativoTto;
    }
    
    public void setAtivoTto(String ativoTto) {
        this.ativoTto = ativoTto;
    }
    }



